<?php
// $Id$
/**
 * @file
 * Creedia distance
 *
 **
 * This module calculates distances between Creedia members.
 *
 * The current metric is counting the common creeds between two members
 *
 * The module:
 *
 * - Keeps distances in a table for easy retrieval
 * - Integrates with Views
 * - Updated by Flag hook
 *
 * The table fields are:
 *
 * uid  - userid
 * mid  - userid
 * cnt  - count of common creeds
 *
 * Profile sharing should be taken into account when showing the
 * distances between members.
 *
 */

/**
 * Implementation of hook_views_api
 */
function cdist_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'cdist'),
  );
}

/**
 * Get distance between two users
 *
 * If user2 is NULL, the distance between user1 and the current logged-in
 * user is returned.
 *
 * If filter is TRUE, the returned distance is filtered according to the
 * current profile sharing settings of $user1:
 * - If user1 profile sharing is set to private (255) distance = 0 is always returned
 * - If user1 profile sharing is set to members-only (2) distance = 0 is returned for anonymous users.
 * - Else the distance is returned
 *
 */
function cdist_dist($uid1, $uid2 = NULL, $filter = TRUE) {

  global $user;

  $uid2 = $uid2 ? $uid2 : $user->uid;

  $sql  = "SELECT cnt FROM {cdist_cache} d WHERE d.uid = %d AND d.mid = %d ";
  $dist = db_result(db_query($sql, $uid1, $uid2));

  if ($filter) {
    $sql  = "SELECT m.field_profile_sharing_value AS share ";
    $sql .= "FROM {content_type_member} m ";
    $sql .= "INNER JOIN {node} n ";
    $sql .= "ON n.nid = m.nid AND n.vid = m.vid ";
    $sql .= "WHERE n.uid = %d";
    $share = db_result(db_query($sql, $uid1));

    if ($share == 255 ||   // If profile is private
    ($share > 0 && !$uid2)) {   // Or if anonymous and profile is only for members
      $dist = NULL;
    }
  }

  return $dist;
}

/**
 * Implementation of hook_menu
 */
function cdist_menu() {
  $items = array();

  $items['admin/content/creedia/cdist/reset'] = array(
        'title'    => 'Reset Distance Cache',
        'description' => 'Reset Distance Cache',
        'page callback' => 'cdist_reset',
        'type'     => MENU_CALLBACK,
        'access arguments' => array('administer site configuration'),
  );
  return $items;

}

/**
 * Implementation of hook_flag
 *
 * Update the distances table once a creed is (de)selected
 */
function cdist_flag($event, $flag, $content_id, $account) {

  if ($flag->name == 'adopt' && $account->uid) {
    // reset cache for specific user
    cdist_update($account->uid);
  }
}


/**
 * Implementation of hook_block
 */
function cdist_block($op = 'list', $delta = 0, $edit = array()) {
  global $user;
  $uid = $user->uid;

  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Creedia: My Way Members');
      $blocks[0]['visibility'] = 1; // show only on listed pages
      $blocks[0]['pages'] = "user/*\n";
      return $blocks;
    case 'configure':
      $form = array();
      return $form;
    case 'save':
      return;
    case 'view': default:
      switch ($delta) {
        case 0:
          if (is_numeric(arg(1))) {
            $title = t('My Way Members');
            $path = 'members/byway';
            $block['subject'] = l('» '. $title, $path, array('attributes' => array('title' => $description)));
            $block['content'] = views_embed_view('Member_blocks', 'block_4', arg(1));
          }
          break;
      }
  }
  return $block;
}


/**
 * Resets the cache and recalculate
 * the distances between all users
 *
 * NOT SCALABLE FOR LARGE NUMBER OF USERS
 * USE CRON INSTEAD
 *
 */
function cdist_reset() {

  // Delete all data from cache
  $sql  = "DELETE FROM {cdist_cache} ";
  db_query($sql);

  // Run over all users and update the cache
  $sql  = "SELECT uid FROM {node} ";
  $sql .= "WHERE type = 'member' AND status = 1 ";
  $result = db_query($sql);
  while ($data = db_fetch_object($result)) {
    cdist_update($data->uid);
  }

  $output = t('Distance between all users was re-calculated.');
  return $output;

}

/**
 * update the distances from a given user
 *
 * called when a adopts a creed to his/her profile
 * called also at intial cache buildup
 *
 * Params: $uid of member
 */
function cdist_update($uid) {

  // Calculate distances of all members to member ($nid, $uid)
  // List only the ones that have common creeds with specified member
  $sql =  "SELECT n.uid, %d AS mid, COUNT(g.content_id) AS cnt ";
  $sql .= "FROM {node} n ";
  $sql .= "INNER JOIN {flag_content} f ";                   // Add content flaged by each member
  $sql .= "ON f.uid = n.uid ";
  //  $sql .= "INNER JOIN {node} c "; // Add node information per each flag (to filter creeds)
  //  $sql .= "ON c.nid = f.content_id ";
  $sql .= "INNER JOIN {flag_content} g ";                   // Add nodes selected by member
  $sql .= "ON f.content_id = g.content_id AND f.fid = g.fid AND g.uid = %d ";  // Creeds selected by uid
  $sql .= "WHERE n.type = 'member' AND n.status = 1 AND n.uid != %d ";         // Don't include self
  //  $sql .= "AND c.type ='creed' AND c.status = 1 ";
  $sql .= "AND f.fid = %d "; // Adopt flag
  $sql .= "GROUP BY n.nid ";

  // get flag info
  $flag = flag_get_flag('adopt');

  if (!db_query_temporary($sql, $uid, $uid, $uid, $flag->fid, 'temp_cdist_cache_'. $uid)) {
    watchdog('creedia', 'CDIST: failed to create temporary table', WATCHDOG_ERROR);
  };

  // Delete all distances from this user
  $sql  = "DELETE FROM {cdist_cache} WHERE uid = %d OR mid = %d";
  db_query($sql, $uid, $uid);

  // Add the newly calculated distances
  $sql  = "INSERT INTO {cdist_cache} SELECT mid, uid, cnt FROM temp_cdist_cache_" . $uid;
  db_query($sql, $uid);
  $sql  = "INSERT INTO {cdist_cache} SELECT uid, mid, cnt FROM temp_cdist_cache_". $uid;
  db_query($sql, $uid);

  return;
}
