<?php
// $Id$
/**
 * @file
 * Creedia front page
 *
 */

if (!defined(CREEDIA_ANNOUNCEMENTS_PER_BLOCK)) {
  define("CREEDIA_ANNOUNCEMENTS_PER_BLOCK", 6);
}

/**
 * Implementation of hook_views_api
 */
function cfront_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'cfront'),
  );
}

/**
 * Implementation of hook_menu
 */
function cfront_menu() {
  $items = array();

  $items['node'] = array(
         'page callback' => 'cfront',
         'type'     => MENU_CALLBACK,
         'access arguments' => array('access content'),
         );

  return $items;
}

/**
 * Implementation of hook_init
 */
function cfront_init() {

  if (drupal_is_front_page()) {
    cfront_add_js();
    drupal_add_feed(url('rss.xml'), t('Creedia Feed'));
  }
}


/**
 * Implementation of hook_block
 */
function cfront_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
  case 'list':
    $blocks[0]['info'] = t('Creedia: Front Info/Register');
    $blocks[1]['info'] = t('Creedia: Front News');
    $blocks[0]['visibility'] = 1; // show only on listed pages
    $blocks[1]['visibility'] = 1; // show only on listed pages
    $blocks[0]['pages'] = "<front>";
    $blocks[1]['pages'] = "<front>";
    return $blocks;
  case 'configure':
    return array();
  case 'save':
    return;
  case 'view': default:
    switch ($delta) {
    case 0:
      $block['content'] .= l(t('Join Us!') .'&nbsp;&nbsp;&nbsp;'. t('Become a member'), 'user/register',
           array('attributes' => array('title' => t('Become a member.')), 'html' => TRUE));
      break;
    case 1:
      $block['content'] = cfront_news();
      break;
    }
    return $block;
  }
}

function cfront() {

  $output = cfront_main();
  $output .= '<div id="front-mission"></div>';
  $output .= cfront_slogan();

  return $output;
}

function cfront_main() {

  $output = '<div id="front-main">';
  $output .= views_embed_view('slideshow_front');
  $output .= '</div>';

  return $output;
}

function cfront_slogan() {

  $output = '<div id="front-slogan">';
  $output .= '<ul class="jsonly">';
  $output .= '<li style="display:none" id="front-slogan-0">'. t('Sharing my world of faith') .'</li>';
  $output .= '<li style="display:none" id="front-slogan-1">'. t('And creating a bridge to others') .'</li>';
  $output .= '<li style="display:none" id="front-slogan-2">'. t('Through exchange of ideas') .'</li>';
  $output .= '<li style="display:none" id="front-slogan-3">'. t('In a global social network.') .'</li>';
  $output .= '</ul>';
  $output .= '</div>';

  return $output;
}

function cfront_add_js() {
  static $js_added = FALSE;

  if (!$js_added) {
    //    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.scrollTo.js');
    //    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.serialScroll.js');
    //    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.bbcnewsticker.js');
    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.li-scroller.js');
    drupal_add_js(drupal_get_path('module', 'cfront') .'/cfront.js');

    $js_added = TRUE;
  }
}

/**
 * News are populated by ajax call to rss.xml
 */
function cfront_news() {

  return '<ul id="news"><li></li></ul>';
}

