<?php
// $Id$
/**
 * @file
 * Creedia front page
 *
 */

if (!defined(CREEDIA_ANNOUNCEMENTS_PER_BLOCK)) {
  define("CREEDIA_ANNOUNCEMENTS_PER_BLOCK", 6);
}

/**
 * Implementation of hook_menu
 */
function cfront_menu() {
  $items = array();

  $items['node'] = array(
         'page callback' => 'cfront',
         'type'     => MENU_CALLBACK,
         'access arguments' => array('access content'),
         );

  return $items;
}

/**
 * Implementation of hook_init
 */
function cfront_init() {

  if (drupal_is_front_page()) {
    cfront_add_js();
    drupal_add_feed(url('rss.xml'), t('Creedia Feed'));
  }
}


/**
 * Implementation of hook_block
 */
function cfront_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
  case 'list':
    $blocks[0]['info'] = t('Creedia: Front Info/Register');
    $blocks[1]['info'] = t('Creedia: Front News');
    $blocks[0]['visibility'] = 1; // show only on listed pages
    $blocks[1]['visibility'] = 1; // show only on listed pages
    $blocks[0]['pages'] = "<front>";
    $blocks[1]['pages'] = "<front>";
    return $blocks;
  case 'configure':
    return array();
  case 'save':
    return;
  case 'view': default:
    switch ($delta) {
    case 0:
      $block['content'] .= l(t('Join Us!') .'&nbsp;&nbsp;&nbsp;'. t('Become a member'), 'user/register',
           array('attributes' => array('title' => t('Become a member.')), 'html' => TRUE));
      break;
    case 1:
      $block['content'] = cfront_news();
      break;
    }
    return $block;
  }
}

function cfront() {

  $output = cfront_main();
  $output .= '<div id="front-mission"></div>';
  $output .= cfront_slogan();

  return $output;
}

function cfront_main() {

  $limit = 17;  // number of slides

  $output = '<div id="front-main">';

  $view = views_create_view('slideshow_front', t('Front Slideshow'));
  views_view_add_block($view, '', 'slideshow_list', $limit, FALSE, FALSE);

  $view->field = array(
      array(
             'tablename' => 'node_data_field_image',
             'field' => 'field_image_fid',
             'label' => '',
             'handler' => 'content_views_field_handler_ungroup',
             'options' => 'slideshow_front_default',
           ),
      );

  views_view_add_filter($view, 'node', 'status', '=', 1, '') ;
  views_view_add_filter($view, 'node', 'type', 'OR', array(0 => 'image_cck'), '') ;
  // slide number field. Image appears only if slide number > 0
  views_view_add_filter($view, 'node_data_field_front_num', 'field_front_num_value_default', '>', 0, '') ;

  views_view_add_sort($view, 'node_data_field_front_num', 'field_front_num_value', 'ASC', '');

  $view->slideshow['timer_delay'] = 3000;

  views_load_cache();
  views_sanitize_view($view);

  $output .= views_build_view('block', $view, array(), $view->use_pager, $view->nodes_per_block);
  $output .= '</div>';

  return $output;
}

function cfront_slogan() {

  $output = '<div id="front-slogan">';
  $output .= '<ul class="jsonly">';
  $output .= '<li style="display:none" id="front-slogan-0">'. t('Sharing my world of faith') .'</li>';
  $output .= '<li style="display:none" id="front-slogan-1">'. t('And creating a bridge to others') .'</li>';
  $output .= '<li style="display:none" id="front-slogan-2">'. t('Through exchange of ideas') .'</li>';
  $output .= '<li style="display:none" id="front-slogan-3">'. t('In a global social network.') .'</li>';
  $output .= '</ul>';
  $output .= '</div>';

  return $output;
}

function cfront_add_js() {
  static $js_added = FALSE;

  if (!$js_added) {
    //    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.scrollTo.js');
    //    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.serialScroll.js');
    //    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.bbcnewsticker.js');
    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.li-scroller.js');
    drupal_add_js(drupal_get_path('module', 'cfront') .'/cfront.js');

    $js_added = TRUE;
  }
}

/**
 * News are populated by ajax call to rss.xml
 */
function cfront_news() {

  return '<ul id="news"><li></li></ul>';
}

