<?php
// $Id$
/* TODO Automatically add Drupal.settings.basePath
   In Drupal 5, you would have to add the base path to Drupal.settings yourself
   if you needed it (it's needed for just about every AHAH/AJAX enabled module
   if you did it right). Now in Drupal 6, it's added automatically. You can always
   find it at Drupal.settings.basePath (actually, as soon as drupal_add_js() is
   called at least once, so this is similar to the way we automatically add
   drupal.js and jquery.js. */

/* TODO FormAPI image buttons are now supported.
   FormAPI now offers the 'image_button' element type, allowing developers to
   use icons or other custom images in place of traditional HTML submit buttons.

$form['my_image_button'] = array(
  '#type'         => 'image_button',
  '#title'        => t('My button'),
  '#return_value' => 'my_data',
  '#src'          => 'my/image/path.jpg',
); */

/* TODO New user_mail_tokens() method may be useful.
   user.module now provides a user_mail_tokens() function to return an array
   of the tokens available for the email notification messages it sends when
   accounts are created, activated, blocked, etc. Contributed modules that
   wish to make use of the same tokens for their own needs are encouraged
   to use this function. */

/* TODO
   There is a new hook_watchdog in core. This means that contributed modules
   can implement hook_watchdog to log Drupal events to custom destinations.
   Two core modules are included, dblog.module (formerly known as watchdog.module),
   and syslog.module. Other modules in contrib include an emaillog.module,
   included in the logging_alerts module. See syslog or emaillog for an
   example on how to implement hook_watchdog.
function example_watchdog($log = array()) {
  if ($log['severity'] == WATCHDOG_ALERT) {
    mysms_send($log['user']->uid,
      $log['type'],
      $log['message'],
      $log['variables'],
      $log['severity'],
      $log['referer'],
      $log['ip'],
      format_date($log['timestamp']));
  }
} */

/* TODO Implement the hook_theme registry. Combine all theme registry entries
   into one hook_theme function in each corresponding module file.
function cfront_theme() {
  return array(
  );
} */

/**
 * @file
 * Creedia front page
 *
 */

if (!defined(CREEDIA_ANNOUNCEMENTS_PER_BLOCK)) {
  define("CREEDIA_ANNOUNCEMENTS_PER_BLOCK", 6);
}

/**
 * Implementation of hook_menu
 */
function cfront_menu() {
  global $user;
  $items = array();
/* TODO
   Non menu code that was placed in hook_menu under the '!$may_cache' block
   so that it could be run during initialization, should now be moved to hook_init.
   Previously we called hook_init twice, once early in the bootstrap process, second
   just after the bootstrap has finished. The first instance is now called boot
   instead of init.
   
   In Drupal 6, there are now two hooks that can be used by modules to execute code
   at the beginning of a page request. hook_boot() replaces hook_boot() in Drupal 5
   and runs on each page request, even for cached pages. hook_boot() now only runs
   for non-cached pages and thus can be used for code that was previously placed in
   hook_menu() with $may_cache = FALSE:
   
   Dynamic menu items under a '!$may_cache' block can often be simplified
   to remove references to arg(n) and use of '%<function-name>' to check
   conditions. See http://drupal.org/node/103114.
   
   The title and description arguments should not have strings wrapped in t(),
   because translation of these happen in a later stage in the menu system.
*/
  if ($may_cache) {
    $items['node'] = array(
		     'page callback' => 'cfront',
		     'type'     => MENU_CALLBACK,
		     'access arguments' => array('access content'),
		     );
  }
  else {
    if (drupal_is_front_page()) {
      cfront_add_js();
      drupal_add_feed(url('rss.xml'), t('Creedia Feed'));
    }
  }
  return $items;
}

/**
 * Implementation of hook_block
 */
function cfront_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
  case 'list':
    $blocks[0]['info'] = t('Creedia: Front Info/Register');
    $blocks[1]['info'] = t('Creedia: Front News');
    $blocks[0]['visibility'] = 1; // show only on listed pages
    $blocks[1]['visibility'] = 1; // show only on listed pages
    $blocks[0]['pages'] = "<front>";
    $blocks[1]['pages'] = "<front>";
    return $blocks;
  case 'configure':
    return array();
  case 'save':
    return;
  case 'view': default:
    switch ($delta) {
    case 0:
      //      $block['content'] = /* TODO
   Please manually fix the parameters on the l() or url() function on the next line.
   Typically, this was not changed because of a function call inside an array call like
   array('title' => t('View user profile.')).*/
l(t('Learn More'), 'about', array('title' => t('Learn More.')));
      $block['content'] .= /* TODO
   Please manually fix the parameters on the l() or url() function on the next line.
   Typically, this was not changed because of a function call inside an array call like
   array('title' => t('View user profile.')).*/
l(t('Join Us!').'&nbsp;&nbsp;&nbsp;'.t('Become a member'), 'user/register', 
			     array('title' => t('Become a member.')), NULL, NULL, FALSE, TRUE);
      break;
    case 1:
      $block['content'] = cfront_news();
      break;
    }
    return $block;
  }
}

function cfront(){

  $output = cfront_main();
  $output .= '<div id="front-mission"></div>';
  $output .= cfront_slogan();

  return $output;
}

function cfront_main() {

  $limit = 17;  // number of slides

  $output = '<div id="front-main">';

  $view = views_create_view('slideshow_front', t('Front Slideshow'));
  views_view_add_block($view, '', 'slideshow_list', $limit, FALSE, FALSE);

  $view->field = array (
			array (
			       'tablename' => 'node_data_field_image',
			       'field' => 'field_image_fid',
			       'label' => '',
			       'handler' => 'content_views_field_handler_ungroup',
			       'options' => 'slideshow_front_default',
			       ),
			);

  views_view_add_filter($view, 'node', 'status', '=', 1, '') ;
  views_view_add_filter($view, 'node', 'type', 'OR', array(0 => 'image_cck'), '') ;
  // slide number field. Image appears only if slide number > 0
  views_view_add_filter($view, 'node_data_field_front_num', 'field_front_num_value_default', '>', 0, '') ;

  views_view_add_sort($view, 'node_data_field_front_num', 'field_front_num_value', 'ASC', '');

  $view->slideshow['timer_delay'] = 3000;

  views_load_cache();
  views_sanitize_view($view);

  $output .= views_build_view('block', $view, array(), $view->use_pager, $view->nodes_per_block);
  $output .= '</div>';

  return $output;
}

function cfront_slogan() {

  $output = '<div id="front-slogan">';
  $output .= '<ul class="jsonly">';
  $output .= '<li style="display:none" id="front-slogan-0">'. t('Sharing my world of faith') .'</li>';
  $output .= '<li style="display:none" id="front-slogan-1">'. t('And creating a bridge to others') .'</li>';
  $output .= '<li style="display:none" id="front-slogan-2">'. t('Through exchange of ideas') .'</li>';
  $output .= '<li style="display:none" id="front-slogan-3">'. t('In a global social network.') .'</li>';
  $output .= '</ul>';
  $output .= '</div>';

  return $output;
}

function cfront_add_js() {
  static $js_added = FALSE;

  if (!$js_added) {
    //    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.scrollTo.js');
    //    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.serialScroll.js');
    //    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.bbcnewsticker.js');
    drupal_add_js(drupal_get_path('module', 'cfront') .'/jquery.li-scroller.js');
    drupal_add_js(drupal_get_path('module', 'cfront') .'/cfront.js');

    $js_added = TRUE;
  }
}

/**
 * News are populated by ajax call to rss.xml
 */
function cfront_news() {

  return '<ul id="news"><li></li></ul>';
}

