<?php
// $Id$
/* TODO Automatically add Drupal.settings.basePath
 In Drupal 5, you would have to add the base path to Drupal.settings yourself
 if you needed it (it's needed for just about every AHAH/AJAX enabled module
 if you did it right). Now in Drupal 6, it's added automatically. You can always
 find it at Drupal.settings.basePath (actually, as soon as drupal_add_js() is
 called at least once, so this is similar to the way we automatically add
 drupal.js and jquery.js. */

/*
 * @file
 * Creedia Virtual Keyboard: adaptation of javascript VirtualKeyboard by
 * WingedFox - Ilya S. Lebedev (Debugger.ru) to Creedia's needs.
 */

/**
 * Implementation of hook_menu().
 */
function cjsvk_menu() {
  $items = array();

  $items['admin/settings/jsvk'] = array(
      'title' => 'Virtual Keyboard',
      'description' => 'Configuration for virtual keyboard',
      'page callback' => 'cjsvk_setup',
  );
  return $items;
}

function cjsvk_setup() {
  $path = drupal_get_path('module', 'cjsvk') .'/js/jsvk/setup/setup.php';
  include($path);
  //  drupal_goto(drupal_get_path('module', 'cjsvk') . '/js/jsvk/setup/setup.php');
}

function cjsvk_add_js($lang = NULL) {

  // layouts per language, as used in VK
  static $layouts = array(
        'zh-hans' => "CN Chinese Cangjie",
        'el' => "GR Greek",
        'he' => "IL Hebrew",
        'hi' => "IN Hindi Traditional",
        'ar' => "IQ Arabic",
        'ja' => "JP Japanese",
        'en' => "US US",
  );
  static $load = TRUE;

  if ($load) {

    // set the default parameter for VK
    $vkpath = drupal_get_path('module', 'cjsvk') .'/js/jsvk/vk_iframe.js';
    $skin = '?vk_skin=textual';
    $layout = $lang ? '&vk_layout="'. $layouts[$lang] .'"' : '&vk_layout="US US"';
    $query = $skin . $layout;
    drupal_add_js($vkpath . $query);

    // load our glue code
    $path = drupal_get_path('module', 'cjsvk') .'/js/cjsvk.js';
    drupal_add_js($path);

    // prepare language settings
    $settings = array('layouts' => array(), 'rtl' => array(), );

    // populate the settings with the listed locales
    $langs = locale_language_list('name', TRUE);
    foreach ($langs as $code => $name) {
      $settings['layouts'][$code] = $layouts[$code];
      $settings['rtl'][$code] = (i18n_language_property($code, 'direction') == LANGUAGE_RTL);
    }
    // add VK configuration
    drupal_add_js(array('jsvk' => $settings), 'setting');

    $load = FALSE;
  }
}
